# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

priortree <- function(cut_lens, alpha = 0.95, beta = 2) {
    .Call('_combr_priortree', PACKAGE = 'combr', cut_lens, alpha, beta)
}

matchesToCor <- function(x) {
    .Call('_combr_matchesToCor', PACKAGE = 'combr', x)
}

